CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar UNIQUE,
  "login_type" varchar,
  "password" varchar,
  "role" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "companies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE,
  "industry_id" integer,
  "name" varchar,
  "website" varchar,
  "descriptions" varchar,
  "logo" varchar,
  "overview" TEXT,
  "perks" TEXT,
  "location" varchar,
  "company_size" varchar,
  "company_type" varchar,
  "working_day" varchar,
  "is_active" bool,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer,
  "title" varchar,
  "slug" varchar,
  "descriptions" varchar,
  "requirement" varchar,
  "quantity" integer,
  "status" varchar,
  "location" varchar,
  "level" varchar,
  "working_model" varchar,
  "min_salary" integer,
  "max_salary" integer,
  "currency_salary" varchar,
  "start_date" timestamp,
  "end_date" timestamp,
  "count_view" integer,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "applications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer,
  "applicant_id" integer,
  "name" varchar,
  "phone" varchar,
  "resume" varchar,
  "status" varchar,
  "cover_letter" varchar,
  "prefer_work_location" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "applicants" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE,
  "first_name" varchar,
  "last_name" varchar,
  "title" varchar,
  "cv" varchar,
  "address" varchar,
  "sex" varchar,
  "website" varchar,
  "phone_number" varchar,
  "summary" varchar,
  "dob" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "applicant_skills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "applicant_id" integer,
  "skill_id" integer,
  "level" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "applicant_experiences" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "applicant_id" integer,
  "title" varchar,
  "company_name" varchar,
  "description" varchar,
  "is_working_here" bool,
  "start_date" timestamp,
  "end_date" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "applicant_educations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "applicant_id" integer,
  "school" varchar,
  "major" varchar,
  "description" varchar,
  "is_current_study" bool,
  "start_date" timestamp,
  "end_date" timestamp,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "industries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "skills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "job_skills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer,
  "skill_id" integer,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "company_reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer,
  "user_id" integer,
  "rate" integer,
  "title" varchar,
  "review" varchar,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "company_follows" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer,
  "user_id" integer,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "company_skills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" integer,
  "skill_id" integer,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "job_views" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer,
  "user_id" integer,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "job_saves" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "job_id" integer,
  "user_id" integer,
  "created_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

ALTER TABLE "companies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "applicants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "jobs" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");

ALTER TABLE "company_reviews" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");

ALTER TABLE "company_follows" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");

ALTER TABLE "companies" ADD FOREIGN KEY ("industry_id") REFERENCES "industries" ("id");

ALTER TABLE "company_reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "company_follows" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "company_skills" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id");

ALTER TABLE "company_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id");

ALTER TABLE "job_views" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "job_saves" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "applications" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id");

ALTER TABLE "job_views" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id");

ALTER TABLE "job_saves" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id");

ALTER TABLE "applications" ADD FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id");

ALTER TABLE "applicant_skills" ADD FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id");

ALTER TABLE "applicant_experiences" ADD FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id");

ALTER TABLE "applicant_educations" ADD FOREIGN KEY ("applicant_id") REFERENCES "applicants" ("id");

ALTER TABLE "applicant_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id");

ALTER TABLE "job_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id");

ALTER TABLE "job_skills" ADD FOREIGN KEY ("job_id") REFERENCES "jobs" ("id");